name: DocPlanner Developer Zone
subtitle: Specyfikacje

baseurl: ''
permalink: /:title
pygments: true
future: true

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
