# Site title and subtitle. This is used in _includes/header.html
name: 'DocPlanner Developer Zone'

# Default categories (in order) to appear in the navigation
sections: [
    ['doc', 'Documentation'],
    ['tut', 'Tutorial'],
    ['ref', 'Reference'],
    ['dev', 'Developers'],
    ['post', 'Posts']
]

layout: documentup
baseurl: ''
permalink: /:title
pygments: true
future: true

#markdown: redcarpet
#redcarpet:
#    extensions: [
#        'no_intra_emphasis',
#        'fenced_code_blocks',
#        'autolink',
#        'strikethrough',
#        'superscript',
#        'with_toc_data',
#        'tables',
#        'hardwrap'
#    ]
